<h2>Informations de livraison</h2>
          <input
            name="prenom"
            type="text"
            class="field"
            placeholder="Prénom"
            required
          />
          <input
            name="nom"
            type="text"
            class="field"
            placeholder="Nom"
            required
          />
          <input
            name="email"
            type="text"
            id="emailAddress"
            class="field"
            placeholder="Votre email"
            required
          />
          <input
            name="confirmationemail"
            id="confirmationemail"
            class="field"
            type="text"
            placeholder="Confirmation email"
            required
          />
          <input
            name="phoneNumber"
            type="text"
            class="field"
            placeholder="Numéro de téléphone"
            required
          />
          <input
            name="ville"
            type="text"
            class="field"
            placeholder="Ville"
            required
          />
          <input
            name="codePostal"
            type="text"
            class="field"
            placeholder="Code Postal"
            required
          />
          <input
            name="adresse"
            type="text"
            class="field"
            placeholder="Adresse"
            required
          />
          <input
            name="adressePlus"
            type="text"
            class="field"
            placeholder="Batiment, étage"
          />
          <textarea
            name="Message"
            id="Message"
            placeholder="Message"
            class="field"
          ></textarea>
          <button
            class="btn"
            type="submit"
            onclick="confirmEmail()"
            value="Envoyer"
          >
            Envoyer
          </button>
